Module 3
YaroslavKust/iTechArt-StudLab pull request #4
Opened 2022-02-15 15:04 UTC by YaroslavKust

2022-02-16 08:24 UTC, mol4 requested changes
Общие замечания:
1.  send.js и getRates.js: Мало смысла в том что бы выделять функции в конкретные модули. Дажи из названия можно понять что с этими модулями что-то не так. Модуль не должен назывться через глагол. Что нужно сделать: Создать общий класс, который будет из себя представлять сервис по работе с api
2. Нет проверок try catch, и обработок ошибок. Для ассинхронных вызовов нужно всегда ожидать что что-то может упасть и думать о том как это обработать и что показать на клиенте

2022-02-16 08:24 UTC, mol4 commented on Module 3/task01_rates/index.js
> +async function mainFunction(){
mainFunction - очень плохое название функцмии - код должен быть само-описываемым

2022-02-16 08:24 UTC, mol4 commented on Module 3/package.json
> +    "build": "webpack",
Было бы неплохо поставить live-server и добавить команду для run  https://www.npmjs.com/package/live-server

2022-02-16 15:31 UTC, YaroslavKust commented
Исправил все ошибки

2022-02-17 06:10 UTC, mol4 approved these changes
Well done!

2022-02-17 06:10 UTC, merged