Resolve task
YaroslavKust/iTechArt-StudLab pull request #6
Opened 2022-03-07 12:25 UTC by YaroslavKust

2022-03-14 11:31 UTC, mol4 requested changes

2022-03-14 11:31 UTC, mol4 commented on Module 4/reddit_posts/src/actions/postListActionCreators.js
> +    console.log("load action");
Needs to delete all console logs in prod version

2022-03-14 11:31 UTC, mol4 commented on Module 4/reddit_posts/src/components/PostDetails.js
> +    if(data != undefined)
The best option is 
`if (data) {}`

2022-03-14 11:31 UTC, mol4 commented on Module 4/reddit_posts/src/components/PostDetails.js
> +const mapStateToProps = state =>(
in function components needs to use the hook - useSelector

2022-03-14 11:31 UTC, mol4 commented on Module 4/reddit_posts/src/components/PostList.js
> +const mapStateToProps = state =>({
useSelector

2022-03-15 11:25 UTC, YaroslavKust commented
fixed

2022-03-18 08:39 UTC, merged